import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, MetaData, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Consistent naming convention so autogenerated constraint names are stable across
# migrations rather than the SQLAlchemy-default random-ish names.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    # Every `TIMESTAMPTZ` column in the migration (Database Spec §0) must correspond to a
    # timezone-*aware* SQLAlchemy DateTime, or binding an aware `datetime.now(timezone.utc)`
    # against what SQLAlchemy infers as a naive column raises at runtime (surfaced by the
    # first real write in a running app, not by a migration or a type checker — caught here
    # via the auth test suite's login flow). Mapping it once at the Base level means every
    # `Mapped[datetime]` / `Mapped[datetime | None]` column across every model gets this
    # automatically, instead of repeating `DateTime(timezone=True)` at each of ~40 columns.
    type_annotation_map = {datetime: DateTime(timezone=True)}


class UUIDPKMixin:
    """Every table's primary key (Database Spec §0): UUID, generated by Postgres."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )


class TenantMixin:
    """Every tenant-scoped table (Database Spec §0): organization_id, always the leading
    column in composite indexes, always enforced by RLS (§0.1) in addition to ORM scoping."""

    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False
    )


class CreatedAtMixin:
    created_at: Mapped[datetime] = mapped_column(server_default=text("now()"), nullable=False)


class UpdatedAtMixin:
    """Maintained via the `set_updated_at` DB trigger (Database Spec §0.3), not application
    code — the server_default here only covers the row's initial insert value."""

    updated_at: Mapped[datetime] = mapped_column(server_default=text("now()"), nullable=False)


class CreatedByMixin:
    created_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=True
    )


class SoftDeleteMixin:
    """30-day recovery window before hard deletion (Blueprint §12.3)."""

    deleted_at: Mapped[datetime | None] = mapped_column(nullable=True)


class StandardAuditMixin(CreatedAtMixin, UpdatedAtMixin, CreatedByMixin, SoftDeleteMixin):
    """The full "audit quad" (Database Spec §0) used by most tenant-scoped tables. Append-only
    or immutable tables (timeline_events, ai_actions, score_history, ...) compose the individual
    mixins above directly instead, since they deliberately omit one or more of these columns."""
